v9.2.1 fixes to octoswarm

diff --git a/octoswarm b/octoswarm
--- a/octoswarm
+++ b/octoswarm
@@ -58,26 +58,48 @@ assert_cluster_json() {
   fi
 }
 
+assert_required_config() {
+  local docker_version
+  docker_version="$(get_docker_version)"
+  if [ "$docker_version" == "null" ]; then
+    fatal "Octoswarm docker version not specified, exiting."
+  fi
+}
+
+assert_required_env() {
+  if [ -z "$OCTOSWARM_GITHUB_API_TOKEN" ]; then
+    fatal "Missing required env OCTOSWARM_GITHUB_API_TOKEN"
+  fi
+}
+
+assert_versions() {
+  local docker_version="$1"
+  local latest_version="$2"
+  if [ -z "$docker_version" ] || [ "$docker_version" == "null" ]; then
+    fatal "Missing '.octoswarm.dockerVersion' in cluster.json"
+  fi
+  if [ -z "$latest_version" ] || [ "$latest_version" == "null" ]; then
+    fatal "Unable to retrieve latest version of octoswarm"
+  fi
+}
+
 get_docker_version() {
   jq --raw-output '.octoswarm.dockerVersion' "$STACK_CONFIG_PATH"
 }
 
 get_binary_name() {
-  local docker_version="$(get_docker_version)"
+  local docker_version
+  docker_version="$(get_docker_version)"
   echo "octoswarm-$docker_version"
 }
 
 get_whalebrew_image() {
-  local docker_version="$(get_docker_version)"
-  local latest_version="$(get_latest_version)"
+  local docker_version
+  local latest_version
+  docker_version="$(get_docker_version)"
+  latest_version="$(get_latest_version)"
+  assert_versions "$docker_version" "$latest_version"
   echo "octoblu/octoswarm:$docker_version-$latest_version"
-}
-
-assert_required_config() {
-  local docker_version="$(get_docker_version)"
-  if [ "$docker_version" == "null" ]; then
-    fatal "Octoswarm docker version not specified, exiting."
-  fi
 }
 
 get_latest_version() {
@@ -104,7 +126,9 @@ main() {
   local args="$@"
   assert_cluster_json
   assert_required_config
-  local binary_name="$(get_binary_name)"
+  assert_required_env
+  local binary_name
+  binary_name="$(get_binary_name)"
 
   if [ "$upgrade" == "true" ]; then
     echo "Uninstalling $binary_name from whalebrew"
@@ -112,7 +136,12 @@ main() {
   fi
 
   if [ -z "$(which "$binary_name" 2> /dev/null)" ]; then
-    local whalebrew_image="$(get_whalebrew_image)"
+    local whalebrew_image
+    whalebrew_image="$(get_whalebrew_image)"
+    if [ "$?" != "0" ]; then
+      errecho "$whalebrew_image"
+      exit 1
+    fi
     echo "Installing $whalebrew_image from whalebrew"
     whalebrew install "$whalebrew_image" \
       && echo "$whalebrew_image installed" \
@@ -120,9 +149,11 @@ main() {
   fi
 
   if [ -z "$args" ]; then
+    echo ''
     usage
     exit 1
   fi
+
   $binary_name $args
 }
 
